# Generated by Django 4.1.3 on 2022-12-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequests',
            name='chat_request',
            field=models.JSONField(default='[]'),
        ),
    ]
