# Generated by Django 4.1.3 on 2022-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_alter_chatrequests_chat_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequests',
            name='chat_request',
            field=models.JSONField(default=list),
        ),
    ]
