# Generated by Django 4.1.3 on 2022-12-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0003_alter_chatrequests_chat_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequests',
            name='request_accept',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chatrequests',
            name='request_reject',
            field=models.JSONField(default=list),
        ),
    ]
