# Generated by Django 4.1.3 on 2022-12-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0005_rename_request_accept_chatrequests_accept_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrequested',
            old_name='chat_request',
            new_name='chat_requested',
        ),
    ]
