# Generated by Django 4.1.3 on 2022-12-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0006_rename_chat_request_chatrequested_chat_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequests',
            name='chat_requested',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Chatrequested',
        ),
    ]
