# Generated by Django 4.1.3 on 2022-12-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0007_chatrequests_chat_requested_delete_chatrequested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField(default=dict)),
            ],
        ),
    ]
