# Generated by Django 4.1.3 on 2022-12-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0008_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrequests',
            old_name='accept',
            new_name='ban',
        ),
        migrations.RenameField(
            model_name='chatrequests',
            old_name='reject',
            new_name='match',
        ),
    ]
