# Generated by Django 4.1.3 on 2022-12-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0012_alter_chatrequests_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequests',
            name='chats',
            field=models.JSONField(default=dict),
        ),
    ]
