# Generated by Django 4.1.3 on 2023-01-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0015_userchat_delete_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchat',
            old_name='users',
            new_name='user',
        ),
    ]
