# Generated by Django 4.1.3 on 2023-01-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0016_rename_users_userchat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchat',
            old_name='chats',
            new_name='chat',
        ),
    ]
