# Generated by Django 4.1.3 on 2023-01-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0018_alter_userchat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrequests',
            name='chats',
        ),
    ]
