# Generated by Django 4.1.3 on 2023-01-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0019_remove_chatrequests_chats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentChats',
        ),
    ]
