# Generated by Django 4.1.3 on 2022-12-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moderator_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
